#!/usr/bin/env python3

import os
import argparse


HEADER = """<!-- Do not edit this file. It is generated with regenerate-qrc.py -->
<!DOCTYPE RCC>
<RCC version="1.0">
    <qresource prefix="/qutepart">"""

FOOTER = """    </qresource>
</RCC>"""

def parse_args():
    parser = argparse.ArgumentParser(description='Regenerate .qrc Qt resource file with list of syntax files')
    parser.add_argument('--xml_path', default='./syntax')
    parser.add_argument('--out_file', default='syntax-files.qrc')
    return parser.parse_args()


def main():
    args = parse_args()

    with open(args.out_file, 'w') as out_file:
        print(HEADER, file=out_file)
        for file_name in os.listdir(args.xml_path):
            if file_name.endswith('.xml'):
                print('        <file>{}/{}</file>'.format(args.xml_path, file_name), file=out_file)
        print(FOOTER, file=out_file)

    print("Done. Do not forget to commit the changes")


main()
